apiVersion: apps/v1
kind: Deployment
metadata:
  name: glados-proxy
  namespace: glados
  labels:
    app: glados-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glados-proxy
  template:
    metadata:
      labels:
        app: glados-proxy
    spec:
      containers:
      - name: glados-proxy
        image: glados-proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5555
          protocol: TCP
          name: glados
        envFrom:
        - configMapRef:
            name: glados-proxy-config
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 5555
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5555
          initialDelaySeconds: 2
          periodSeconds: 5
