apiVersion: apps/v1
kind: Deployment
metadata:
  name: glados-web-frontend
  namespace: glados
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glados-web-frontend
  template:
    metadata:
      labels:
        app: glados-web-frontend
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: frontend
        image: fabbricca/glados-web-frontend:latest
        command: ["/bin/sh", "-c"]
        args: ["chmod -R 755 /usr/share/nginx/html && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
