apiVersion: v1
kind: Service
metadata:
  name: glados-proxy
  namespace: glados
  labels:
    app: glados-proxy
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: 5555
    protocol: TCP
    name: glados
  selector:
    app: glados-proxy
