apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cognitia-auth-ingress
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-auth
    app.kubernetes.io/part-of: cognitia
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - auth.cognitia.iberu.me
      secretName: auth-cognitia-tls
  rules:
    - host: auth.cognitia.iberu.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cognitia-auth
                port:
                  number: 8000
