apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cognitia
resources:
  - namespace.yaml
  - api-configmap.yaml
  - api-secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/managed-by: flux
