apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cognitia
resources:
  # PostgreSQL database
  - postgres-pvc.yaml
  - postgres-secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  # API server
  - api-pvc.yaml
  - api-configmap.yaml
  - api-secret.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/managed-by: flux
