apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agnost-studio
  namespace: agnost
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: letsencrypt-wildcard-cert
      hosts:
        - agnost.iberu.me
  rules:
    - host: agnost.iberu.me
      http:
        paths:
          - path: /studio
            pathType: Prefix
            backend:
              service:
                name: studio
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: studio
                port:
                  number: 4000